upstream dis_cluster {
    server digital-instrument-service:8087;
    server digital-instrument-service-2:8087;
}

server {
    listen 8090;

    client_max_body_size 15m;  # Support additional document uploads (max 10MB + base64 overhead)

    location / {
        proxy_pass http://dis_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
    }
}
